name: tests

on: [ push, pull_request ]

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "tests"
        run: ./gradlew test
